### ISSUE TITLE
how to use npm ebuild script? 

### ISSUE THREAD

**Issue by cnscorpions** [ShanikaNishadhi/Electron-React-Boilerplate#1]
very good posting. But how to use ebuild ? 

when I run `yarn ebuild`, it throws error:
'node_modules\.bin\build' is not recognized as an internal or external command,
operable program or batch file.

OS: win10 Pro
Node v12.13.0.
npm 6.14.5
create-react-app 
react v16.13.1

**Comment by mtalhagaoglu** [comment]
i have same problem... how can build this project as electron app?

**Comment by cnscorpions** [comment]
It's a disaster to build a electron app. 😂

**Comment by vettorazi** [comment]
Why did you close @cnscorpions ?
Posting 'It's a disaster to build a electron app. 😂' doesn't help others.
